---
application:
  name: 'sigle'
  project: 'sigle-app'
  organization: 'QoveryCommunity'
  dockerfile: Dockerfile
  publicly_accessible: true
routers:
  - name: 'main-sigle'
    custom_domains:
      - branch: main
        domain: dev.sigle.io
      # - branch: feature/qovery-setup
      #   domain: beta.sigle.io
    routes:
      - application_name: 'sigle'
        paths:
          - '/'
