[build]
builder = "DOCKERFILE"
watchPatterns = ["/apps/server-next/**"]
dockerfilePath = "/apps/server-next/Dockerfile"

[deploy]
region = "us-west2"
runtime = "V2"
numReplicas = 1
healthcheckPath = "/health"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 300
restartPolicyMaxRetries = 5
